spring:
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      database: ${env.MONGO_DATABASE}
      uri: mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${env.GOOGLE_CLIENT_ID}
            clientSecret: ${env.GOOGLE_CLIENT_SECRET}

jwt:
  secret-key: ${env.JWT_SECRET}
  access-token-validity: 86400000  # 24 hours
  refresh-token-validity: 604800000 # 7 days